### ISSUE TITLE
(Problem) There is a cycle in the graph. It is not possible to derive a topological sort

### ISSUE THREAD

**Issue by rstormsf** [alcuadrado/truffle-flattener#9]
```Error: There is a cycle in the graph. It is not possible to derive a topological sort.```

works fine if I use solidity_flattener.
any ideas? 
I will be able to share sources after audit is done

**Comment by alcuadrado** [comment]
`solidity_flattener` uses the binary version of `solc`, which I want to avoid doing. I'll investigate more about how to support cyclic dependencies when I have some free time.

**Comment by rstormsf** [comment]
Any progress on this @alcuadrado

**Comment by alcuadrado** [comment]
There's no easy way of solving cyclic dependencies. 

For getting this working you should parse the files in the cycle and merge their AST in the right order. This is out of scope of what I have in mind for this tool: concat the required files, but in a way that it's easy to map sections of the output to actual files. Keep in mind that this tool is mostly for debugging and merging different files will make debugging harder.

Still, if someone is up for implementing this in a way that doesn't alter the not-in-a-cycle parts of the output I'll happily review it and merge it. I opened #14 to track this, so I'm closing this issue.
